version: '3.8'

services:
  worker:
    build: .
    container_name: katago-worker
    environment:
      - REDIS_URL=redis://:blackrice123@${REDIS_HOST:-127.0.0.1}:6379
      - MONGODB_URI=${MONGODB_URI}
      - KATAGO_API_URL=${KATAGO_API_URL:-http://127.0.0.1:8080}
    restart: always
    network_mode: "host" # 方便访问同机的 KataGo 容器和外部 Redis
